export const MODAL_TYPES = {
  CREATE_STORE: "CREATE_STORE",
  EDIT_OPTIONS: "EDIT_OPTIONS",
  DELETE_ATTRIBUTE: "DELETE_ATTRIBUTE",
  OPEN_WALLET: "OPEN_WALLET",
  SETTINGS: {
    ADD_LOCATION: "ADD_LOCATION",
    ADD_USER: "ADD_USER",
    ADD_PromoCode: "ADD_PromoCode"
  },
  WALLET: {
    VIEW_WALLET: "VIEW_WALLET",
    ADD_CARD: "WALLET_ADD_CARD",
    ADD_CREDIT: "WALLET_ADD_CREDIT",
    VIEW_ADD_ONS: "WALLET_VIEW_ADD_ONS",
    VIEW_INVOICES: "WALLET_VIEW_INVOICES",
  },
};
