export const AVATAR_IMAGE_SIZE_LIMIT = 250000;

export const defaultDropDownValue = 1;

export const currencies = [
  { label: "USD", value: "USD" },
  { label: "AED", value: "AED" },
  { label: "AFN", value: "AFN" },
  { label: "ALL", value: "ALL" },
  { label: "AMD", value: "AMD" },
  { label: "ANG", value: "ANG" },
  { label: "AOA", value: "AOA" },
  { label: "ARS", value: "ARS" },
  { label: "AUD", value: "AUD" },
  { label: "AWG", value: "AWG" },
  { label: "AZN", value: "AZN" },
  { label: "BAM", value: "BAM" },
  { label: "BBD", value: "BBD" },
  { label: "BDT", value: "BDT" },
  { label: "BIF", value: "BIF" },
  { label: "BMD", value: "BMD" },
  { label: "BND", value: "BND" },
  { label: "BOB", value: "BOB" },
  { label: "BRL", value: "BRL" },
  { label: "BSD", value: "BSD" },
  { label: "BWP", value: "BWP" },
  { label: "BZD", value: "BZD" },
  { label: "CAD", value: "CAD" },
  { label: "CDF", value: "CDF" },
  { label: "CHF", value: "CHF" },
  { label: "CLP", value: "CLP" },
  { label: "CNY", value: "CNY" },
  { label: "CRC", value: "CRC" },
  { label: "CVE", value: "CVE" },
  { label: "CZK", value: "CZK" },
  { label: "DJF", value: "DJF" },
  { label: "DKK", value: "DKK" },
  { label: "DOP", value: "DOP" },
  { label: "DZD", value: "DZD" },
  { label: "EGP", value: "EGP" },
  { label: "ETB", value: "ETB" },
  { label: "EUR", value: "EUR" },
  { label: "FJD", value: "FJD" },
  { label: "FKP", value: "FKP" },
  { label: "GBP", value: "GBP" },
  { label: "GEL", value: "GEL" },
  { label: "GIP", value: "GIP" },
  { label: "GMD", value: "GMD" },
  { label: "GNF", value: "GNF" },
  { label: "GTQ", value: "GTQ" },
  { label: "GYD", value: "GYD" },
  { label: "HKD", value: "HKD" },
  { label: "HNL", value: "HNL" },
  { label: "HRK", value: "HRK" },
  { label: "HTG", value: "HTG" },
  { label: "HUF", value: "HUF" },
  { label: "IDR", value: "IDR" },
  { label: "ILS", value: "ILS" },
  { label: "INR", value: "INR" },
  { label: "ISK", value: "ISK" },
  { label: "JMD", value: "JMD" },
  { label: "JPY", value: "JPY" },
  { label: "KES", value: "KES" },
  { label: "KGS", value: "KGS" },
  { label: "KHR", value: "KHR" },
  { label: "KMF", value: "KMF" },
  { label: "KRW", value: "KRW" },
  { label: "KYD", value: "KYD" },
  { label: "KZT", value: "KZT" },
  { label: "LAK", value: "LAK" },
  { label: "LBP", value: "LBP" },
  { label: "LKR", value: "LKR" },
  { label: "LRD", value: "LRD" },
  { label: "LSL", value: "LSL" },
  { label: "MAD", value: "MAD" },
  { label: "MDL", value: "MDL" },
  { label: "MKD", value: "MKD" },
  { label: "MMK", value: "MMK" },
  { label: "MNT", value: "MNT" },
  { label: "MOP", value: "MOP" },
  { label: "MRO", value: "MRO" },
  { label: "MUR", value: "MUR" },
  { label: "MVR", value: "MVR" },
  { label: "MWK", value: "MWK" },
  { label: "MXN", value: "MXN" },
  { label: "MYR", value: "MYR" },
  { label: "MZN", value: "MZN" },
  { label: "NAD", value: "NAD" },
  { label: "NGN", value: "NGN" },
  { label: "NIO", value: "NIO" },
  { label: "NOK", value: "NOK" },
  { label: "NPR", value: "NPR" },
  { label: "NZD", value: "NZD" },
  { label: "PAB", value: "PAB" },
  { label: "PEN", value: "PEN" },
  { label: "PGK", value: "PGK" },
  { label: "PHP", value: "PHP" },
  { label: "PKR", value: "PKR" },
  { label: "PLN", value: "PLN" },
  { label: "PYG", value: "PYG" },
  { label: "QAR", value: "QAR" },
  { label: "RON", value: "RON" },
  { label: "RSD", value: "RSD" },
  { label: "RUB", value: "RUB" },
  { label: "RWF", value: "RWF" },
  { label: "SAR", value: "SAR" },
  { label: "SBD", value: "SBD" },
  { label: "SCR", value: "SCR" },
  { label: "SEK", value: "SEK" },
  { label: "SGD", value: "SGD" },
  { label: "SHP", value: "SHP" },
  { label: "SLL", value: "SLL" },
  { label: "SOS", value: "SOS" },
  { label: "SRD", value: "SRD" },
  { label: "STD", value: "STD" },
  { label: "SZL", value: "SZL" },
  { label: "THB", value: "THB" },
  { label: "TJS", value: "TJS" },
  { label: "TOP", value: "TOP" },
  { label: "TRY", value: "TRY" },
  { label: "TTD", value: "TTD" },
  { label: "TWD", value: "TWD" },
  { label: "TZS", value: "TZS" },
  { label: "UAH", value: "UAH" },
  { label: "UGX", value: "UGX" },
  { label: "UYU", value: "UYU" },
  { label: "UZS", value: "UZS" },
  { label: "VND", value: "VND" },
  { label: "VUV", value: "VUV" },
  { label: "WST", value: "WST" },
  { label: "XAF", value: "XAF" },
  { label: "XCD", value: "XCD" },
  { label: "XOF", value: "XOF" },
  { label: "XPF", value: "XPF" },
  { label: "YER", value: "YER" },
  { label: "ZAR", value: "ZAR" },
  { label: "ZMW", value: "ZMW" }
];

export const times = [
  "00:00",
  "00:30",
  "01:00",
  "01:30",
  "02:00",
  "02:30",
  "03:00",
  "03:30",
  "04:00",
  "04:30",
  "05:00",
  "05:30",
  "06:00",
  "06:30",
  "07:00",
  "07:30",
  "08:00",
  "08:30",
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30",
  "19:00",
  "19:30",
  "20:00",
  "20:30",
  "21:00",
  "21:30",
  "22:00",
  "22:30",
  "23:00",
  "23:30"
];

export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];

export const stripeUrl =
  "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_EB73NQ9BccjniMBt5byhpk62c9bIz3wY&scope=read_write";

export const unitsOfDiscount = [
  { label: "%", value: 0 },
  { label: "$", value: 1 }
];
